# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{event_calendar}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason LaPier", "Jeremiah Heller"]
  s.date = %q{2010-11-02}
  s.description = %q{Provides basic event management features with versioned history of changes.}
  s.email = ["jason.lapier@gmail.com", "jeremiah@inertialbit.net"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
     "Gemfile.lock",
     "README",
     "Rakefile",
     "VERSION",
     "app/controllers/application_controller.rb",
     "app/controllers/attendees_controller.rb",
     "app/controllers/event_calendar/application_controller.rb",
     "app/controllers/event_revisions_controller.rb",
     "app/controllers/events_controller.rb",
     "app/helpers/event_calendar/application_helper.rb",
     "app/helpers/events_helper.rb",
     "app/models/attendee.rb",
     "app/models/deletable_instance_methods.rb",
     "app/models/event.rb",
     "app/models/event_revision.rb",
     "app/models/participant.rb",
     "app/models/participator.rb",
     "app/views/attendees/index.html.erb",
     "app/views/attendees/new.html.erb",
     "app/views/event-calendar-shared/_flash.html.erb",
     "app/views/event-calendar-shared/_main_menu.html.erb",
     "app/views/event-calendar-shared/_navigation.html.erb",
     "app/views/event_revisions/index.html.erb",
     "app/views/event_revisions/show.html.erb",
     "app/views/events/_browse_event_revisions.html.erb",
     "app/views/events/_event.html.erb",
     "app/views/events/_event_details.html.erb",
     "app/views/events/_form.html.erb",
     "app/views/events/attendees.html.erb",
     "app/views/events/edit.html.erb",
     "app/views/events/index.html.erb",
     "app/views/events/new.html.erb",
     "app/views/events/search.html.erb",
     "app/views/events/show.html.erb",
     "app/views/layouts/application.html.erb",
     "config/application.rb",
     "config/blueprint_settings.yml",
     "config/boot.rb",
     "config/cucumber.yml",
     "config/database.example.yml",
     "config/database.yml",
     "config/environment.rb",
     "config/environments/development.rb",
     "config/environments/production.rb",
     "config/environments/test.rb",
     "config/initializers/backtrace_silencers.rb",
     "config/initializers/formtastic.rb",
     "config/initializers/inflections.rb",
     "config/initializers/mime_types.rb",
     "config/initializers/secret_token.rb",
     "config/initializers/session_store.rb",
     "config/locales/en.yml",
     "config/routes.rb",
     "db/migrate/20101011142543_create_events.rb",
     "db/migrate/20101011172027_create_attendees.rb",
     "db/migrate/20101011200048_make_events_revisable.rb",
     "db/schema.rb",
     "db/seeds.rb",
     "lib/event_calendar.rb",
     "lib/event_calendar/action_view.rb",
     "lib/event_calendar/asset_path.rb",
     "lib/event_calendar/engine.rb",
     "lib/generators/event_calendar/install/USAGE",
     "lib/generators/event_calendar/install/install_generator.rb",
     "lib/generators/event_calendar/install/templates/event_calendar.rake",
     "lib/tasks/blueprint.rake",
     "lib/tasks/cucumber.rake",
     "public/404.html",
     "public/422.html",
     "public/500.html",
     "public/favicon.ico",
     "public/images/rails.png",
     "public/javascripts/application.js",
     "public/javascripts/behaviors.js",
     "public/javascripts/fullcalendar.js",
     "public/javascripts/jquery-1.4.2.min.js",
     "public/javascripts/jquery-ui-1.7.2.custom.min.js",
     "public/javascripts/jquery.clonePosition.js",
     "public/javascripts/jquery.qtip-1.0.0-rc3.js",
     "public/javascripts/jquery.string.1.0-min.js",
     "public/javascripts/jquery.tablesorter.min.js",
     "public/javascripts/lowpro.jquery.js",
     "public/javascripts/rails.js",
     "public/robots.txt",
     "public/stylesheets/application.css",
     "public/stylesheets/blueprint/grid.css",
     "public/stylesheets/blueprint/icons/cross.png",
     "public/stylesheets/blueprint/icons/doc.png",
     "public/stylesheets/blueprint/icons/email.png",
     "public/stylesheets/blueprint/icons/external.png",
     "public/stylesheets/blueprint/icons/feed.png",
     "public/stylesheets/blueprint/icons/im.png",
     "public/stylesheets/blueprint/icons/key.png",
     "public/stylesheets/blueprint/icons/pdf.png",
     "public/stylesheets/blueprint/icons/tick.png",
     "public/stylesheets/blueprint/icons/visited.png",
     "public/stylesheets/blueprint/icons/xls.png",
     "public/stylesheets/blueprint/ie.css",
     "public/stylesheets/blueprint/plugins/buttons/icons/cross.png",
     "public/stylesheets/blueprint/plugins/buttons/icons/key.png",
     "public/stylesheets/blueprint/plugins/buttons/icons/tick.png",
     "public/stylesheets/blueprint/plugins/buttons/readme.txt",
     "public/stylesheets/blueprint/plugins/buttons/screen.css",
     "public/stylesheets/blueprint/plugins/fancy-type/readme.txt",
     "public/stylesheets/blueprint/plugins/fancy-type/screen.css",
     "public/stylesheets/blueprint/plugins/link-icons/icons/doc.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/email.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/external.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/feed.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/im.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/pdf.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/visited.png",
     "public/stylesheets/blueprint/plugins/link-icons/icons/xls.png",
     "public/stylesheets/blueprint/plugins/link-icons/readme.txt",
     "public/stylesheets/blueprint/plugins/link-icons/screen.css",
     "public/stylesheets/blueprint/plugins/rtl/readme.txt",
     "public/stylesheets/blueprint/plugins/rtl/screen.css",
     "public/stylesheets/blueprint/plugins/silksprite/sprite.css",
     "public/stylesheets/blueprint/plugins/silksprite/sprites.png",
     "public/stylesheets/blueprint/print.css",
     "public/stylesheets/blueprint/readme.txt",
     "public/stylesheets/blueprint/screen.css",
     "public/stylesheets/error_messages.css",
     "public/stylesheets/formtastic.css",
     "public/stylesheets/formtastic_changes.css",
     "public/stylesheets/fullcalendar.css",
     "public/stylesheets/fullcalendar_changes.css",
     "public/stylesheets/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png",
     "public/stylesheets/smoothness/images/ui-bg_flat_75_ffffff_40x100.png",
     "public/stylesheets/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png",
     "public/stylesheets/smoothness/images/ui-bg_glass_65_ffffff_1x400.png",
     "public/stylesheets/smoothness/images/ui-bg_glass_75_dadada_1x400.png",
     "public/stylesheets/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png",
     "public/stylesheets/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png",
     "public/stylesheets/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png",
     "public/stylesheets/smoothness/images/ui-icons_222222_256x240.png",
     "public/stylesheets/smoothness/images/ui-icons_2e83ff_256x240.png",
     "public/stylesheets/smoothness/images/ui-icons_454545_256x240.png",
     "public/stylesheets/smoothness/images/ui-icons_888888_256x240.png",
     "public/stylesheets/smoothness/images/ui-icons_cd0a0a_256x240.png",
     "public/stylesheets/smoothness/jquery-ui-1.7.2.custom.css",
     "public/stylesheets/tablesorter/blue/asc.gif",
     "public/stylesheets/tablesorter/blue/bg.gif",
     "public/stylesheets/tablesorter/blue/desc.gif",
     "public/stylesheets/tablesorter/blue/style.css",
     "public/stylesheets/text_and_colors.css",
     "spec/controllers/attendees_controller_spec.rb",
     "spec/controllers/event_revisions_controller_spec.rb",
     "spec/controllers/events_controller_spec.rb",
     "spec/fixtures/events.yml",
     "spec/models/deletable_instance_methods_spec.rb",
     "spec/models/event_revision_spec.rb",
     "spec/models/event_spec.rb",
     "spec/spec_helper.rb",
     "spec/spec_helpers/mocks.rb",
     "vendor/plugins/searchable_by/MIT-LICENSE",
     "vendor/plugins/searchable_by/README",
     "vendor/plugins/searchable_by/Rakefile",
     "vendor/plugins/searchable_by/init.rb",
     "vendor/plugins/searchable_by/install.rb",
     "vendor/plugins/searchable_by/lib/searchable_by.rb",
     "vendor/plugins/searchable_by/tasks/searchable_by_tasks.rake",
     "vendor/plugins/searchable_by/test/boot.rb",
     "vendor/plugins/searchable_by/test/database.yml",
     "vendor/plugins/searchable_by/test/fixtures/companies.yml",
     "vendor/plugins/searchable_by/test/fixtures/company.rb",
     "vendor/plugins/searchable_by/test/fixtures/employee.rb",
     "vendor/plugins/searchable_by/test/fixtures/employees.yml",
     "vendor/plugins/searchable_by/test/fixtures/schema.rb",
     "vendor/plugins/searchable_by/test/helper.rb",
     "vendor/plugins/searchable_by/test/lib/activerecord_test_case.rb",
     "vendor/plugins/searchable_by/test/lib/activerecord_test_connector.rb",
     "vendor/plugins/searchable_by/test/lib/load_fixtures.rb",
     "vendor/plugins/searchable_by/test/searchable_by_test.rb",
     "vendor/plugins/searchable_by/uninstall.rb"
  ]
  s.homepage = %q{http://github.com/inertialbit/event_calendar}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple versioned event management for Rails 3.}
  s.test_files = [
    "spec/controllers/attendees_controller_spec.rb",
     "spec/controllers/event_revisions_controller_spec.rb",
     "spec/controllers/events_controller_spec.rb",
     "spec/models/deletable_instance_methods_spec.rb",
     "spec/models/event_revision_spec.rb",
     "spec/models/event_spec.rb",
     "spec/spec_helper.rb",
     "spec/spec_helpers/mocks.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.1"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_runtime_dependency(%q<prarupa>, [">= 0"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_runtime_dependency(%q<formtastic>, [">= 0"])
      s.add_runtime_dependency(%q<acts_as_revisable>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, ["= 2.0.1"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.1"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<prarupa>, [">= 0"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_dependency(%q<formtastic>, [">= 0"])
      s.add_dependency(%q<acts_as_revisable>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, ["= 2.0.1"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.1"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<prarupa>, [">= 0"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    s.add_dependency(%q<formtastic>, [">= 0"])
    s.add_dependency(%q<acts_as_revisable>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, ["= 2.0.1"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

