# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{event_calendar_engine}
  s.version = "0.2.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason LaPier", "Jeremiah Heller"]
  s.date = %q{2011-04-06}
  s.description = %q{Provides basic event management features with versioned history of changes.}
  s.email = ["jason.lapier@gmail.com", "jeremiah@inertialbit.net"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README",
    "Rakefile",
    "VERSION",
    "app/controllers/application_controller.rb",
    "app/controllers/attendees_controller.rb",
    "app/controllers/event_calendar/application_controller.rb",
    "app/controllers/event_revisions_controller.rb",
    "app/controllers/events_controller.rb",
    "app/controllers/links_controller.rb",
    "app/helpers/event_calendar/application_helper.rb",
    "app/helpers/events_helper.rb",
    "app/models/attendee.rb",
    "app/models/deletable_instance_methods.rb",
    "app/models/event.rb",
    "app/models/event_instance_methods.rb",
    "app/models/event_revision.rb",
    "app/models/link.rb",
    "app/models/participant.rb",
    "app/models/participator.rb",
    "app/views/attendees/_add_attendees.html.erb",
    "app/views/attendees/index.html.erb",
    "app/views/attendees/new.html.erb",
    "app/views/event-calendar-shared/_flash.html.erb",
    "app/views/event-calendar-shared/_main_menu.html.erb",
    "app/views/event-calendar-shared/_navigation.html.erb",
    "app/views/event_revisions/_event_revision.html.erb",
    "app/views/event_revisions/_list_group.html.erb",
    "app/views/event_revisions/index.html.erb",
    "app/views/event_revisions/show.html.erb",
    "app/views/events/_browse_event_revisions.html.erb",
    "app/views/events/_calendar.html.erb",
    "app/views/events/_current_event.html.erb",
    "app/views/events/_details.html.erb",
    "app/views/events/_event.html.erb",
    "app/views/events/_event_details.html.erb",
    "app/views/events/_form.html.erb",
    "app/views/events/_list.html.erb",
    "app/views/events/_list_group.html.erb",
    "app/views/events/_multi_day_list_event.html.erb",
    "app/views/events/_one_day_list_event.html.erb",
    "app/views/events/_search_form.html.erb",
    "app/views/events/attendees.html.erb",
    "app/views/events/edit.html.erb",
    "app/views/events/index.html.erb",
    "app/views/events/new.html.erb",
    "app/views/events/search.html.erb",
    "app/views/events/show.html.erb",
    "app/views/layouts/application.html.erb",
    "app/views/links/_form.html.erb",
    "app/views/links/_link.html.erb",
    "app/views/links/_links.html.erb",
    "app/views/links/create.js.rjs",
    "app/views/links/edit.html.erb",
    "app/views/links/new.html.erb",
    "app/views/links/show.html.erb",
    "app/views/links/update.js.rjs",
    "config/application.rb",
    "config/blueprint_settings.yml",
    "config/boot.rb",
    "config/cucumber.yml",
    "config/database.example.yml",
    "config/environment.rb",
    "config/environments/development.rb",
    "config/environments/production.rb",
    "config/environments/test.rb",
    "config/initializers/backtrace_silencers.rb",
    "config/initializers/constants.rb",
    "config/initializers/formtastic.rb",
    "config/initializers/inflections.rb",
    "config/initializers/mime_types.rb",
    "config/initializers/secret_token.rb",
    "config/initializers/session_store.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "db/migrate/20101011142543_create_events.rb",
    "db/migrate/20101011172027_create_attendees.rb",
    "db/migrate/20101011200048_make_events_revisable.rb",
    "db/migrate/20101223221015_change_start_on_end_on_to_timestamp.rb",
    "db/migrate/20101223233354_add_timezone_to_events.rb",
    "db/migrate/20110204223256_add_presenters_facilitators_to_events.rb",
    "db/migrate/20110206000427_create_event_calendar_links.rb",
    "db/schema.rb",
    "db/seeds.rb",
    "lib/event_calendar.rb",
    "lib/event_calendar/engine.rb",
    "lib/generators/event_calendar/install/USAGE",
    "lib/generators/event_calendar/install/install_generator.rb",
    "lib/generators/event_calendar/install/templates/event_calendar.rake",
    "lib/tasks/blueprint.rake",
    "lib/tasks/cucumber.rake",
    "public/404.html",
    "public/422.html",
    "public/500.html",
    "public/favicon.ico",
    "public/javascripts/event_calendar/event_calendar.js",
    "public/javascripts/event_calendar/event_calendar_behaviors.js",
    "public/javascripts/event_calendar/fullcalendar.js",
    "public/javascripts/event_calendar/jquery-ui-1.7.2.custom.min.js",
    "public/javascripts/event_calendar/jquery.clonePosition.js",
    "public/javascripts/event_calendar/jquery.js",
    "public/javascripts/event_calendar/jquery.qtip-1.0.0-rc3.js",
    "public/javascripts/event_calendar/jquery.string.1.0-min.js",
    "public/javascripts/event_calendar/jquery.tablesorter.min.js",
    "public/javascripts/event_calendar/lowpro.jquery.js",
    "public/javascripts/event_calendar/rails.js",
    "public/robots.txt",
    "public/stylesheets/event_calendar/blueprint/grid.css",
    "public/stylesheets/event_calendar/blueprint/icons/cross.png",
    "public/stylesheets/event_calendar/blueprint/icons/doc.png",
    "public/stylesheets/event_calendar/blueprint/icons/email.png",
    "public/stylesheets/event_calendar/blueprint/icons/external.png",
    "public/stylesheets/event_calendar/blueprint/icons/feed.png",
    "public/stylesheets/event_calendar/blueprint/icons/im.png",
    "public/stylesheets/event_calendar/blueprint/icons/key.png",
    "public/stylesheets/event_calendar/blueprint/icons/pdf.png",
    "public/stylesheets/event_calendar/blueprint/icons/tick.png",
    "public/stylesheets/event_calendar/blueprint/icons/visited.png",
    "public/stylesheets/event_calendar/blueprint/icons/xls.png",
    "public/stylesheets/event_calendar/blueprint/ie.css",
    "public/stylesheets/event_calendar/blueprint/print.css",
    "public/stylesheets/event_calendar/blueprint/readme.txt",
    "public/stylesheets/event_calendar/blueprint/screen.css",
    "public/stylesheets/event_calendar/error_messages.css",
    "public/stylesheets/event_calendar/formtastic.css",
    "public/stylesheets/event_calendar/formtastic_changes.css",
    "public/stylesheets/event_calendar/fullcalendar.css",
    "public/stylesheets/event_calendar/fullcalendar_changes.css",
    "public/stylesheets/event_calendar/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-bg_flat_75_ffffff_40x100.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-bg_glass_65_ffffff_1x400.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-bg_glass_75_dadada_1x400.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-icons_222222_256x240.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-icons_2e83ff_256x240.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-icons_454545_256x240.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-icons_888888_256x240.png",
    "public/stylesheets/event_calendar/smoothness/images/ui-icons_cd0a0a_256x240.png",
    "public/stylesheets/event_calendar/smoothness/jquery-ui-1.7.2.custom.css",
    "public/stylesheets/event_calendar/tablesorter/blue/asc.gif",
    "public/stylesheets/event_calendar/tablesorter/blue/bg.gif",
    "public/stylesheets/event_calendar/tablesorter/blue/desc.gif",
    "public/stylesheets/event_calendar/tablesorter/blue/style.css",
    "public/stylesheets/event_calendar/text_and_colors.css",
    "vendor/plugins/searchable_by/MIT-LICENSE",
    "vendor/plugins/searchable_by/README",
    "vendor/plugins/searchable_by/Rakefile",
    "vendor/plugins/searchable_by/init.rb",
    "vendor/plugins/searchable_by/install.rb",
    "vendor/plugins/searchable_by/lib/searchable_by.rb",
    "vendor/plugins/searchable_by/tasks/searchable_by_tasks.rake",
    "vendor/plugins/searchable_by/test/boot.rb",
    "vendor/plugins/searchable_by/test/database.yml",
    "vendor/plugins/searchable_by/test/fixtures/companies.yml",
    "vendor/plugins/searchable_by/test/fixtures/company.rb",
    "vendor/plugins/searchable_by/test/fixtures/employee.rb",
    "vendor/plugins/searchable_by/test/fixtures/employees.yml",
    "vendor/plugins/searchable_by/test/fixtures/schema.rb",
    "vendor/plugins/searchable_by/test/helper.rb",
    "vendor/plugins/searchable_by/test/lib/activerecord_test_case.rb",
    "vendor/plugins/searchable_by/test/lib/activerecord_test_connector.rb",
    "vendor/plugins/searchable_by/test/lib/load_fixtures.rb",
    "vendor/plugins/searchable_by/test/searchable_by_test.rb",
    "vendor/plugins/searchable_by/uninstall.rb"
  ]
  s.homepage = %q{http://github.com/inertialbit/event_calendar}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Simple versioned event management for Rails 3.}
  s.test_files = [
    "spec/controllers/attendees_controller_spec.rb",
    "spec/controllers/event_revisions_controller_spec.rb",
    "spec/controllers/events_controller_spec.rb",
    "spec/controllers/links_controller_spec.rb",
    "spec/fixtures/event_calendar_events.yml",
    "spec/fixtures/event_calendar_events_links.yml",
    "spec/fixtures/event_calendar_links.yml",
    "spec/helpers/event_calendar/application_helper_spec.rb",
    "spec/models/deletable_instance_methods_spec.rb",
    "spec/models/event_instance_methods_spec.rb",
    "spec/models/event_revision_spec.rb",
    "spec/models/event_spec.rb",
    "spec/models/link_spec.rb",
    "spec/spec_helper.rb",
    "spec/spec_helpers/helpers.rb",
    "spec/spec_helpers/mocks.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<formtastic>, [">= 0"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_runtime_dependency(%q<prarupa>, [">= 0"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_runtime_dependency(%q<event_calendar_engine>, [">= 0"])
      s.add_runtime_dependency(%q<acts_as_revisable>, [">= 0"])
      s.add_development_dependency(%q<engineer>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, ["= 3.0.3"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_runtime_dependency(%q<prarupa>, [">= 0"])
      s.add_runtime_dependency(%q<formtastic>, [">= 0"])
      s.add_runtime_dependency(%q<acts_as_revisable>, [">= 0"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
    else
      s.add_dependency(%q<formtastic>, [">= 0"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<prarupa>, [">= 0"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_dependency(%q<event_calendar_engine>, [">= 0"])
      s.add_dependency(%q<acts_as_revisable>, [">= 0"])
      s.add_dependency(%q<engineer>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rails>, ["= 3.0.3"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<prarupa>, [">= 0"])
      s.add_dependency(%q<formtastic>, [">= 0"])
      s.add_dependency(%q<acts_as_revisable>, [">= 0"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<acts_as_fu>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
    end
  else
    s.add_dependency(%q<formtastic>, [">= 0"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<prarupa>, [">= 0"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    s.add_dependency(%q<event_calendar_engine>, [">= 0"])
    s.add_dependency(%q<acts_as_revisable>, [">= 0"])
    s.add_dependency(%q<engineer>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rails>, ["= 3.0.3"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<prarupa>, [">= 0"])
    s.add_dependency(%q<formtastic>, [">= 0"])
    s.add_dependency(%q<acts_as_revisable>, [">= 0"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<acts_as_fu>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
  end
end

